import React from 'react'
import NavbarHome from './Header/NavbarHome'
import Footer from './Footer/Footer';
function TermsAndConditions() {
    return (
        <div className="terms">
            <NavbarHome/>
            <div className="terms__content">
                <div className="terms__contentHeader">
                    Terms & Conditions
                </div>
                <div className="terms__body">
                    <p className="terms__para_one">
                    This document is an electronic record in terms of Information Technology Act, 2000 and rules thereunder, as applicable and the amended provisions pertaining to electronic records in various statutes, as amended from time to time by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                    </p>
                    <p className="terms__para_one">
                    This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that requires publishing of the rules and regulations, privacy policy and Terms of Use for access or usage of www.pharmeasy.in website and its mobile applications.
                    </p>
                    <div className="terms__pointOne">
                        1.&nbsp;<span className="pointData">GENERAL</span>

                    </div>
                    <p className="terms__para_one"> MedicalCare, an internet based portal and Medical Care, a mobile application, (hereinafter together be referred to as “Website") is run, operated and maintained by Axelia Solutions Private Limited (hereinafter to be referred as “Company” or “We” or “Our” or “Us”), a company duly incorporated under the provisions of the Companies Act, 2013.</p>
                    <p className="terms__para_one">Use of the Website is offered to You, subject to acceptance of all the terms, conditions and notices contained in these Terms including applicable policies which are incorporated herein by reference, along with any amendments / modifications made time to time by Company at its sole discretion and posted on the Website, including by way of imposing an additional charge for access to or use of a service(s).</p>
                    <p className="terms__para_one">For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on the Website by providing Account Information (defined below) while registering on the Website as a registered User using the computer systems.</p>
                    <p className="terms__para_one">Company shall not be required to notify You, whether as a registered user or not, of any changes made to the Terms and Conditions ("Terms"). The revised Terms shall be made available on the Website. Your use of the Website and the Services is subject to the most current version of the Terms made available on the Website, at the time of such use. You are requested to regularly visit the Website to view the most current Terms. It shall be Your responsibility to check the Terms periodically for changes. Company may require You to provide Your consent to the updated Terms in a specified manner prior to any further use of the Website and the Services, provided on the Website. If no such separate consent is sought, Your continued use of the Website, following changes to the Terms, will constitute your express acceptance of those changes.</p>
                    <p className="terms__para_one">By (i) using this Website or any facility or service provided by this Website in any way; or (ii) merely by browsing the Website, You agree that you have read, understood and agreed to be bound by, including without limitation, by these Terms, the Website's Privacy Policy. and such other rules, guidelines, policies, terms and conditions as are relevant under the applicable law(s) in India and other jurisdictions, for the purposes of accessing, browsing or transacting on the Website, or availing any of the Services, and such rules, guidelines, policies, terms and conditions shall be deemed to be incorporated into, and considered as part and parcel of these Terms of Use.</p>
                    <p className="terms__para_one">Company shall not be liable to deliver any Products purchased by You for delivery, in locations outside US.</p>
                    <p className="terms__para_one">The User agrees to use the service to authorise an individual and get the products from the third party on his/her behalf.</p>
                </div>
            </div>
            <Footer/>
        </div>
    );
}

export default TermsAndConditions;
